# Generated by Django 4.2.7 on 2023-11-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalumnos', '0003_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
